---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trace-data-pvc
  namespace: airflow-cluster
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi